### ISSUE TITLE
Blur happens also in children

### ISSUE THREAD

**Issue by KirkBushman** [chrisbanes/haze#78] opened 2024-01-04 16:30 UTC
Hey :) 

I'm trying to apply the blur effect on the below case:

![Screenshot_20240104-171256](https://github.com/chrisbanes/haze/assets/20772090/22709d5c-de1a-4f99-b7b9-428d8d5d821d)

I have a face to face call, the feed is almost edge-to-edge with a control bar at the bottom. I'm trying to have Haze blur the rounded background but I get this effect instead.

I can still see the feed through, but the controls are being blurred instead.

Here is how I'm achieving this:

```
// On the root composable
val hazeState = remember { HazeState() }

BoxWithConstraints(
    contentAlignment = Alignment.Center,
    modifier = Modifier
        .fillMaxSize()
        .background(MyTheme.colors.background)
        .haze(
            state = hazeState,
            backgroundColor = MyTheme.colors.backgroundControls,
        )
```  

```
// On the control background
Box(
    modifier = Modifier
        .matchParentSize()
        .padding(
            start = horizontalPadding,
            end = horizontalPadding,
            bottom = MyTheme.grid.unitFactor(2.5f),
         )
         .hazeChild(
             state = hazeState,
             shape = MyTheme.shapes.roundRad16,
         )
         .background(
             color = MyTheme.colors.backgroundControls,
             shape = MyTheme.shapes.roundRad16,
         )
         .padding(
             top = MyTheme.grid.unitFactor(2.5f),
             start = MyTheme.grid.unitFactor(3f),
             end = MyTheme.grid.unitFactor(3f),
             bottom = MyTheme.grid.unitFactor(2.5f),
          ),
 ) {}
```  

Is it even possible to do it with haze? can you exclude children composables?
Is the SurfaceView underneath disrupting the modifier?

**Comment by chrisbanes** [comment] 2024-01-04 17:04
> Is the SurfaceView underneath disrupting the modifier?

Not sure, but I don't believe so.

> Is it even possible to do it with haze? can you exclude children composables?

No, the `haze` and `hazeChild` need to be siblings and not descendants of each other, otherwise the child will be blurred, as you've found. I assume that the `Box` is a child of the `BoxWithConstraints`?

**Comment by chrisbanes** [comment] 2024-01-05 11:15
Closing this as working as intended. Feel free to comment if there's anything else.

**Closed by chrisbanes** 2024-01-05 11:15 UTC

**Comment by KirkBushman** [comment] 2024-01-08 10:20
@chrisbanes I tried to put the haze and hazeChild element next to each other, but it didn't work. I'm trying to make the haze effect take the colours from an active RTC video feed but make it fully transparent. There seems to be an issue with a setup using an AndroidView/SurfaceView. :((

I might have to give up on it and use an opaque colour instead.

Here below my setup:
```
AndroidView(
    factory = { context ->
        val frameLayout = FrameLayout(context)
        val surfaceView = videoRenderHelper.setupRemoteVideo(
            uid = partner.id,
            renderMode = videoSizeHelper.calculateRenderMode(state, uiState, agoraState),
        )
        frameLayout.addView(surfaceView, 0)
        frameLayout
    },
    modifier = Modifier
         .haze(
              state = hazeState,
              backgroundColor = MyTheme.colors.backgroundControls,
         )
    )
}
```

Also, I think that having the .haze() and .hazeChild() composables always as siblings is pretty limiting. It makes it difficult to use in cases when you need AnimatedVisibility... or any custom composable that wraps your blurred item.

Could the HazeState be changed in the future to remember the references to the background and child, so it can be used in a nested way?

Thank you in advance for your help, 
and for creating this library.

**Comment by chrisbanes** [comment] 2024-01-08 10:55
Simple answer, no. It's just the way that Haze needs to work. We're basically doing our own (very limited) windowing, and I don't plan on doing anything more complex.

**Comment by KirkBushman** [comment] 2024-01-08 11:09
@chrisbanes I thought so, thanks anyway for your work. I think this is still a great library for simpler use cases. 😃
