### ISSUE TITLE
edge blending options and/or blur the edges 

### ISSUE THREAD

**Issue by MagenL** [chrisbanes/haze#141] opened 2024-02-27 20:21 UTC
## Information

  - Haze version: 0.5.3
  - Platform: Android

Hi Chris,
first, thanks to this amazing library that does an incredible job, and also thanks to all the other contributors for making the impossible - possible in Android Blur issues.
This is not a classic issue or issue at all it is more like a feature request, if I missed the doc about it (I hope not), I couldn't blend/level the corners, so when using shapes (unique or regular) the edges are very noticeable.
it would be great if the library could offer such a mechanic to make the edges less noticeable.
it will help a lot if it will be possible

thanks again for the amazing work :)

**Comment by chrisbanes** [comment] 2024-02-28 08:28
This sounds like a duplicate of #132 ?

**Comment by MagenL** [comment] 2024-02-28 19:59
ok, so I added 2 pictures, 
1. the first one is a regular implementation of haze- 
<img width="905" alt="basic blur" src="https://github.com/chrisbanes/haze/assets/85404436/e9a91698-f203-4b63-8857-d1c73aab866b">
as you can see in the above picture, the blur is at the same level from the center to the edges, which makes it very noticeable. and for some scenarios, we need the blur to integrate into the view 

2. in this picture, I added some hacky, bad implementation of haze using a for loop over shapes to make the blurred edges less noticeable and somewhat leveling from center to the edge - 
<img width="875" alt="lessNoticableBlur" src="https://github.com/chrisbanes/haze/assets/85404436/d3372902-d518-4389-b11c-39d091c94775">

It could be very useful if we could make the blur spot from the center and get less and less noticeable to the edges.

**Comment by chrisbanes** [comment] 2024-02-28 21:34
I'm afraid that the APIs we have available don't easily support radial blurring.

There might be some clever ways to implement this via a runtime shader, but it would be difficult to do that across all platforms.

I think this is basically infeasible. If anyone thinks of a good to handle this, PRs welcome!

**Closed** 2024-02-28 21:34 UTC
